### ISSUE TITLE
Login not working from simulator

### ISSUE THREAD

**Issue by benpackard** [facebook/facebook-objc-sdk#1056] opened 2019-09-26 02:14 UTC
- Xcode Version: `11.1`
- Swift Version: `5.1`
- Installation Platform & Verison: `Cocoapods` version `5.6.0`

## Goals

Test Facebook log in using the iOS simulator.

## Expected Results

The Facebook log in prompt opens.

## Actual Results

Nothing happens. No user object is returned (of course) and no error is returned.

## Steps to Reproduce

1. Attempt to log in via Facebook on device and confirm that everything works as expected.
2. Attempt to log in via the simulator and observe that nothing happens.

**Comment by kazenokage** [comment] 2019-09-26 14:19
What iOS version are you targetting? I've run into same kind of issues after building for iOS 13 and I'm still looking for a solution 🤔

**Comment by benpackard** [comment] 2019-09-26 14:24
I've replicated this on the iOS 13.1 but as of this morning I'm not experiencing the issue - I have made exactly zero code changes. I was very careful to test this last night, perhaps something on the backend was tweaked?

**Comment by dreamolight** [comment] 2019-09-27 06:12
We were not able to reproduce this issue and we didn't find any server side change that could affect simulator only. So closing this for now, feel free to re-open it if you could still reproduce. And please make sure you're on latest SDK version as we shipped a few fixes for Login in recent releases.

**Closed by dreamolight** 2019-09-27 06:12 UTC
